apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskmanager.fullname" . }}-backend
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
    {{- include "taskmanager.backend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "taskmanager.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskmanager.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.registry }}/{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "taskmanager.fullname" . }}-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskmanager.fullname" . }}-secret
                  key: SECRET_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "taskmanager.fullname" . }}-secret
                  key: DB_PASSWORD
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/v1/auth/token/
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/auth/token/
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
