apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskmanager.fullname" . }}-config
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.config.debug | quote }}
  ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsOrigins | quote }}
