apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "taskmanager.fullname" . }}-media
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backend.media.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.backend.media.storage }}
