apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "taskmanager.postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
